config/routes.rb
Rails.application.routes.draw do
  root to: 'front/posts#index'

  namespace :admin do
    root to: 'admin_site#index'

    get 'users/:id/reset_password_from_email/:key' => 'users#reset_password', as: 'reset_password_from_email'
    get 'users/:id/accept_invitation_from_email/:key' => 'users#accept_invitation', :as => 'accept_invitation_from_email'
    get 'users/:id/activate_from_email/:key' => 'users#activate', :as => 'activate_from_email'

    resources :users, :only => [] do
      collection do
        get 'first'
      end
      member do
        put 'accept_invitation', :action => 'do_accept_invitation'
        get 'accept_invitation'
        put 'reset_password', :action => 'do_reset_password'
        get 'reset_password'
      end
    end
  end

  scope :admin do
    get 'users/:id/account' => 'admin/users#account', :as => 'account_user'
    post 'login' => 'admin/users#login', :as => 'user_login_post'
    get 'login' => 'admin/users#login', :as => 'user_login'
    get 'logout' => 'admin/users#logout', :as => 'user_logout'
    get 'forgot_password' => 'admin/users#forgot_password', :as => 'user_forgot_password'
    post 'forgot_password' => 'admin/users#forgot_password', :as => 'user_forgot_password_post'
  end

  scope module: 'front' do
    get 'about' => 'static#about', as: 'about_page'
    get 'contact' => 'static#contact', as: 'contact_page'
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create]
      collection do
        get :search
      end
      member do
        post :comment
        get :comment, to: redirect(path: '/posts/%{id}')
        get :preview
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  hobo_model # Don't put anything above this

  fields do
    title :string, :required, null: false
    state :string, :required, null: false, default: 'draft'
    published_at :datetime
    body :text, null: false
    excerpt :text
    markdown_body :text, :required, null: false
    markdown_excerpt :text
    timestamps
  end
  attr_accessible :title, :published_at, :author, :author_id, :category, :category_id, :picture, :picture_id, :body, :markdown_body, :excerpt, :markdown_excerpt, :state

  include OrderQuery
  include PgSearch

  belongs_to :author, class_name: 'User', inverse_of: :posts, creator: true
  belongs_to :picture, class_name: 'Asset', inverse_of: :posts
  belongs_to :category, inverse_of: :posts
  has_many :comments, -> { reorder(:created_at, :id) }, inverse_of: :post

  validate :validate_markdown_fields

  before_save :update_html_from_markdown

  order_query :published_at_order, [:published_at, :desc], [:id, :desc]
  default_scope -> { order(created_at: :desc) }
  scope :published, -> { where(state: 'published') }
  pg_search_scope :search_by_content,
                  against: {title: 'A', excerpt: 'B', body: 'C'},
                  using: {tsearch: Rails.configuration.pg_tsearch}

  def to_param
    "#{id}-#{title.parameterize}"
  end

  # --- Permissions --- #

  def create_permitted?
    acting_user.signed_up?
  end

  def update_permitted?
    acting_user.signed_up?
  end

  def destroy_permitted?
    acting_user.signed_up?
  end

  def view_permitted?(field)
    acting_user.signed_up?
  end

  private

  def markdown_parser(renderer)
    Redcarpet::Markdown.new(renderer, tables: true, autolink: true)
  end

  def error_raising_renderer
    @error_raising_renderer ||= markdown_parser(CustomMarkdownRenderer.new { |error| raise error })
  end

  def update_html_from_markdown
    self.body = error_raising_renderer.render(markdown_body) if markdown_body_changed?
    self.excerpt = error_raising_renderer.render(markdown_excerpt) if markdown_excerpt_changed?
  end

  def validate_markdown_fields
    [:markdown_body, :markdown_excerpt].each do |field|
      next unless public_send(:"#{field}_changed?")
      markdown_parser(CustomMarkdownRenderer.new { |error| errors.add(field, error.to_s) })
          .render(public_send(field))
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminSiteController

  hobo_model_controller

  auto_actions :all
  
end

app/controllers/front/base_controller.rb
module Front
  class BaseController < ApplicationController
    layout 'front'
  end
end

app/controllers/front/posts_controller.rb
module Front
  class PostsController < BaseController
    include HoboPermissionsHelper

    def collection
      Post.unscoped.published
    end

    def index
      @posts = collection.published_at_order.includes(:author, :picture)
    end

    def show
      @post = collection.find(params[:id])
      unless params[:id] == @post.to_param
        redirect_to post_url(@post)
        return
      end
      load_show_records
      @comment = Comment.new
    end

    def preview
      raise AbstractController::ActionNotFound unless logged_in?
      @post = Post.unscoped.find(params[:id])
      unless @post.state == 'published' || current_user.administrator? || @post.author == current_user
        raise ActionController::Forbidden
      end
      redirect_to preview_post_url(@post) unless params[:id] == @post.to_param
    end

    def comment
      @post = collection.find(params[:id])
      @comment = Comment.new(params.require(:comment).permit(:guest_name, :guest_email, :guest_website, :body))
      @comment.post = @post
      @comment.author = current_user if logged_in?
      if @comment.save
        redirect_to post_url(@post, anchor: "comment-#{@comment.id}")
      else
        load_show_records
        render :show
      end
    end

    def search
      @search_query = params[:query].strip
      @posts = collection.includes(:author).search_by_content(@search_query).with_pg_search_highlight
    end

    private

    def load_show_records
      @post.comments.includes(:author).load
      qp = collection.published_at_order_at(@post)
      @prev_post = qp.previous(false)
      @next_post = qp.next(true)
    end
  end
end

app/controllers/front/static_controller.rb
module Front
  class StaticController < BaseController
    def home
    end

    def about
    end

    def contact
    end
  end
end

app/helpers/front/base_helper.rb
module Front
  module BaseHelper
    def caption(textid)
      caption = Caption.find_by_textid(textid)
      if caption && !caption.body.blank?
        block_given? ? yield(caption.body) : caption.body
      else
        textid
      end
    end

    def nav_entry(label, path, current_page_options = {})
      html_class = (controller_path == current_page_options[:controller] || current_page_options[:controller].nil?) &&
          (action_name == current_page_options[:action] || current_page_options[:action].nil?) &&
          !current_page_options.empty? ?
                       'current' : nil
      content_tag(:li, class: html_class) do
        link_to t(label), path
      end
    end

    def gravatar_hash(email)
      Digest::MD5.hexdigest(email.strip.downcase)
    end

    def gravatar_avatar_url(email)
      'https://www.gravatar.com/avatar/' + gravatar_hash(email) + '?' + {s: 50, d: 'blank'}.to_query
    end

    def gravatar_jsonp_url(email, callback)
      'https://www.gravatar.com/' + gravatar_hash(email) + '.json?' + {callback: callback}.to_query
    end
  end
end

app/views/front/posts/_comment.html.erb
<li id="comment-<%= comment.id %>" data-gravatar-hash="<%= gravatar_hash(comment.email) %>">
  <div class="avatar">
    <%= image_tag(gravatar_avatar_url(comment.email), class: 'avatar', alt: '') %>
  </div>

  <div class="comment-info">
    <cite><%= comment.name %></cite>
    <% if comment.guest_website %>
      &ndash;
      <%= link_to(comment.guest_website, comment.guest_website) %>
    <% elsif comment.author %>
      &ndash;
      <%= link_to(caption('site.title'), root_path) %>
    <% end %>

    <div class="comment-meta">
      <time class="comment-time" datetime="<%= l(comment.created_at, format: :iso) %>">
        <%= l(comment.created_at, format: :long) %>
      </time>
    </div>
  </div>

  <div class="comment-text">
    <%= simple_format(h(comment.body)) %>
  </div>

  <%= javascript_include_tag(gravatar_jsonp_url(comment.email, 'gravatarProfileCallback'), defer: 'defer') %>
</li>

app/views/front/posts/_comment_form.html.erb
<div id="add-comment" class="respond">
  <h3><%= t('front.comments.label.add_comment') %></h3>
  <%= form_for(@comment, url: comment_post_path(@post, anchor: 'add-comment')) do |comment_form| %>
    <% if @comment.errors.any? %>
      <div class="validation-errors">
        <%= t('front.comments.form.validation_errors') %>:
        <ul>
          <% @comment.errors.full_messages.each do |message| %>
            <li><%=message%></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if logged_in? %>
      <div class="bio">
        <div class="avatar">
          <%= image_tag(gravatar_avatar_url(current_user.email_address), class: 'avatar', alt: '') %>
        </div>

        <div class="comment-info">
          <%= t('front.comments.label.comment_as') %>:<br />
          <cite><%= current_user.name %></cite>
        </div>
      </div>
    <% else %>
      <div class="cf">
        <%= comment_form.label :guest_name do %>
          <%= t('activerecord.attributes.comment.guest_name') %> <span class="required">*</span>
        <% end %>
        <%= comment_form.text_field :guest_name %>
      </div>
      <div class="cf">
        <%= comment_form.label :guest_email do %>
          <%= t('activerecord.attributes.comment.guest_email') %> <span class="required">*</span>
          <span><%= t('front.comments.label.email_note').html_safe %></span>
        <% end %>
        <%= comment_form.email_field :guest_email %>
      </div>
      <div class="cf">
        <%= comment_form.label :guest_website %>
        <%= comment_form.text_field :guest_website %>
      </div>
    <% end %>
    <div class="message cf">
      <%= comment_form.label :body do %>
        <%= t('activerecord.attributes.comment.body') %> <span class="required">*</span>
      <% end %>
      <%= comment_form.text_area :body %>
    </div>
    <%= comment_form.submit t('front.comments.form.submit') %>
  <% end %>
</div>

app/views/front/posts/_search_form.html.erb
<%= form_tag(search_posts_path, method: 'get', enforce_utf8: false) do %>
  <%= text_field_tag(:query, @search_query,
                     class: 'text-search',
                     placeholder: t('front.search.placeholder'),
                     onfocus: "this.placeholder = ''",
                     onblur: "this.placeholder = '#{j(t('front.search.placeholder'))}'") %>
  <%= submit_tag('', name: nil, class: 'submit-search') %>
<% end %>

app/views/front/posts/_search_widget.html.erb
<div class="widget widget_search">
  <h5><%= t('front.search.label') %></h5>
  <%= render 'search_form' %>
</div>

app/views/front/posts/index.html.erb
<% content_for(:site_title_prefix) { t('front.nav.blog') } %>
<% content_for(:site_header) { caption('headers.blog').html_safe } %>

<div class="content-outer">
  <div id="page-content" class="row">
    <div id="primary" class="eight columns">
      <% @posts.each do |post| %>
        <article class="post">
          <div class="entry-header cf">
            <h1><%= link_to(post.title, post_path(post)) %></h1>
            <p class="post-meta">
              <time class="date" datetime="<%= l(post.published_at, format: :iso) %>">
                <%= l(post.published_at.to_date, format: :long) %>
              </time>
              /
              <span><%= post.author.name %></span>
            </p>
          </div>

          <% if post.picture && post.picture.asset.exists?(:medium) # TODO: Think about separate size class.  %>
            <div class="post-thumb">
              <% picture = post.picture.asset %>
              <%= link_to(image_tag(picture.url(:medium), alt: picture.original_filename, title: post.title), post_path(post)) %>
            </div>
          <% end %>

          <div class="post-content">
            <%
              post_excerpt = Nokogiri::HTML::fragment(post.excerpt)
              last_child = post_excerpt.at_css('p:last-child')
              last_child = post_excerpt unless last_child
              last_child.add_child("\n" + link_to(t('front.nav.read_more') + content_tag(:i, nil, class: 'fa fa-arrow-circle-o-right'), post_path(post), class: 'more-link'))
              post_excerpt = post_excerpt.to_html
            %>
            <%= post_excerpt.html_safe %>
          </div>
        </article>
      <% end %>
    </div>

    <div id="secondary" class="four columns end">
      <aside id="sidebar">
        <%= render 'search_widget' %>
      </aside>
    </div>

  </div>
</div>

<script>
    $(document).ready(function () {
        $('.post-content').lightGallery({
            selector: 'figure > a',
            hideBarsDelay: 3000,
            speed: 400
        });
    });
</script>

app/views/front/posts/preview.html.erb
<% content_for(:site_title_prefix) { @post.title } %>
<% content_for(:site_header) { caption('headers.blog').html_safe } %>

<div class="content-outer">
  <div id="page-content" class="row">
    <div id="primary" class="eight columns">
      <article class="post">
        <% unless @post.state == 'published' %>
          <div class="alert"><%= t('front.posts.draft_alert') %></div>
        <% end %>

        <div class="entry-header cf">
          <h1><%= @post.title %></h1>
          <p class="post-meta">
            <time class="date" datetime="<%= l(@post.published_at, format: :iso) %>">
              <%= l(@post.published_at, format: :long) %>
            </time>
            /
            <span><%= @post.author.name %></span>
          </p>
        </div>

        <% if @post.picture && @post.picture.asset.exists?(:medium) %>
          <div class="post-thumb">
            <% picture = @post.picture.asset %>
            <%= image_tag(picture.url(:medium), alt: picture.original_filename, title: @post.title) %>
          </div>
        <% end %>

        <div class="post-content">
          <%= @post.body.html_safe %>
        </div>
      </article>
    </div>

    <div id="secondary" class="four columns end">
      <aside id="sidebar">
        <%= render 'search_widget' %>
      </aside>
    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        $('.post-content').lightGallery({
            selector: 'figure > a',
            hideBarsDelay: 3000,
            speed: 400
        });
    });
</script>

app/views/front/posts/search.html.erb
<% content_for(:site_title_prefix) { '%s "%s"' % [t('front.search.results'), @search_query] } %>
<% content_for(:site_header) { caption('headers.search').html_safe } %>

<div id="journal" class="search-results">

  <div class="row" id="sidebar">
    <div class="twelve columns widget widget_search">
      <%= render 'search_form' %>
      <h1>
        <% if @posts.empty? %>
          <%= t('front.search.no_results') %> &ldquo;<%= @search_query %>&rdquo;.
        <% else %>
          <%= t('front.search.results') %> &ldquo;<%= @search_query %>&rdquo;:
        <% end %>
      </h1>
    </div>
  </div>

  <div class="blog-entries">
    <% @posts.each do |post| %>
      <article class="row entry">
        <div class="entry-header">
          <div class="ten columns entry-title pull-right">
            <h3><%= link_to(post.title, post_path(post)) %></h3>
          </div>
          <div class="two columns post-meta end">
            <time class="post-date" datetime="<%= l(post.published_at, format: :iso) %>">
              <%= l(post.published_at.to_date, format: :long) %>
            </time>
            <span class="dauthor"><%= post.author.name %></span>
          </div>
        </div>
        <div class="ten columns offset-2 post-content">
          <p>
            <%= post.pg_search_highlight.html_safe %>
            <%= link_to(t('front.nav.go_to_post') + content_tag(:i, nil, class: 'fa fa-arrow-circle-o-right'), post_path(post), class: 'more-link') %>
          </p>
        </div>
      </article>
    <% end %>
  </div>
</div>

app/views/front/posts/show.html.erb
<% content_for(:site_title_prefix) { @post.title } %>
<% content_for(:site_header) { caption('headers.blog').html_safe } %>

<div class="content-outer">
  <div id="page-content" class="row">
    <div id="primary" class="eight columns">
      <article class="post">
        <div class="entry-header cf">
          <h1><%= @post.title %></h1>
          <p class="post-meta">
            <time class="date" datetime="<%= l(@post.published_at, format: :iso) %>">
              <%= l(@post.published_at, format: :long) %>
            </time>
            /
            <span><%= @post.author.name %></span>
          </p>
        </div>

        <% if @post.picture && @post.picture.asset.exists?(:medium) %>
          <div class="post-thumb">
            <% picture = @post.picture.asset %>
            <%= image_tag(picture.url(:medium), alt: picture.original_filename, title: @post.title) %>
          </div>
        <% end %>

        <div class="post-content">
          <%= @post.body.html_safe %>
        </div>

        <ul class="post-nav cf">
          <% if @prev_post %>
            <li class="prev">
              <%= link_to(post_path(@prev_post), rel: 'prev') do%>
                <strong><%= t('front.nav.previous_post') %></strong> <%= @prev_post.title %>
            <% end %>
            </li>
          <% end %>
          <% if @next_post %>
            <li class="next">
              <%= link_to(post_path(@next_post), rel: 'next') do %>
                <strong><%= t('front.nav.next_post') %></strong> <%= @next_post.title %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </article>

      <div id="comments">
        <h3><%= t('front.comments.count', count: @post.comments.count) %></h3>
        <ol class="commentlist">
          <%= render partial: 'comment', collection: @post.comments %>
        </ol>
        <%= render partial: 'comment_form' %>
      </div>
    </div>

    <div id="secondary" class="four columns end">
      <aside id="sidebar">
        <%= render 'search_widget' %>
      </aside>
    </div>
  </div>
</div>

<script>
    function gravatarProfileCallback(profile) {
        var profile = profile.entry[0];
        if(profile == null || profile.requestHash == null)
            return;
        console.log(profile);
        $('#comments ol.commentlist > li')
            .filter(function () {
                return this.dataset.gravatarHash === profile.requestHash;
            })
            .each(function () {
               var self = $(this);
               var anchor = document.createElement('a');
               anchor.href = profile.profileUrl;
               anchor.title = '<%= j(t('front.comments.label.gravatar_profile')) %>: ' + profile.displayName;
               self.find('.avatar > img').wrap(anchor);
               self.find('.comment-info > cite').wrap(anchor);
            });
    }

    $(document).ready(function () {
        $('.post-content').lightGallery({
            selector: 'figure > a',
            hideBarsDelay: 3000,
            speed: 400
        });
    });
</script>