config/routes.rb
Rails.application.routes.draw do
  root to: 'front/posts#index'

  namespace :admin do
    root to: 'admin_site#index'

    get 'users/:id/reset_password_from_email/:key' => 'users#reset_password', as: 'reset_password_from_email'
    get 'users/:id/accept_invitation_from_email/:key' => 'users#accept_invitation', :as => 'accept_invitation_from_email'
    get 'users/:id/activate_from_email/:key' => 'users#activate', :as => 'activate_from_email'

    resources :users, :only => [] do
      collection do
        get 'first'
      end
      member do
        put 'accept_invitation', :action => 'do_accept_invitation'
        get 'accept_invitation'
        put 'reset_password', :action => 'do_reset_password'
        get 'reset_password'
      end
    end
  end

  scope :admin do
    get 'users/:id/account' => 'admin/users#account', :as => 'account_user'
    post 'login' => 'admin/users#login', :as => 'user_login_post'
    get 'login' => 'admin/users#login', :as => 'user_login'
    get 'logout' => 'admin/users#logout', :as => 'user_logout'
    get 'forgot_password' => 'admin/users#forgot_password', :as => 'user_forgot_password'
    post 'forgot_password' => 'admin/users#forgot_password', :as => 'user_forgot_password_post'
  end

  scope module: 'front' do
    get 'about' => 'static#about', as: 'about_page'
    get 'contact' => 'static#contact', as: 'contact_page'
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create]
      collection do
        get :search
      end
      member do
        post :comment
        get :comment, to: redirect(path: '/posts/%{id}')
        get :preview
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HobosBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta name="description" content="<%= caption('site.description') %>">
  <meta name="keywords" content="<%= caption('site.keywords') %>">
  <meta name="author" content="<%= caption('site.author') %>">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <title>
    <% if content_for?(:site_title_prefix) %>
      <%= yield(:site_title_prefix) %> &ndash;
    <% end %>
    <%= caption('site.title') %>
  </title>

  <% caption('site.ga_tracking_id') do |ga_tracking_id| %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ga_tracking_id %>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '<%= j(ga_tracking_id) %>');
    </script>
  <% end %>

  <%= stylesheet_link_tag 'front', media: 'all' %>
  <%= javascript_include_tag 'front' %>
  <% [192, 16, 32].each do |size| %>
    <%= favicon_link_tag "favicon-#{size}x#{size}.png", type: 'image/png', sizes: "#{size}x#{size}" %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div class="row">
    <div class="twelve columns">
      <div class="logo">
        <%= link_to(image_tag('/images/logo.png', alt: caption('site.title'), title: t('front.nav.blog')), posts_path) %>
      </div>

      <nav id="nav-wrap">
        <a class="mobile-btn" href="#nav-wrap" title="<%= t('front.nav.show_nav') %>"><%= t('front.nav.show_nav') %></a>
        <a class="mobile-btn" href="#" title="<%= t('front.nav.hide_nav') %>"><%= t('front.nav.hide_nav') %></a>
        <ul id="nav" class="nav">
          <%= nav_entry('front.nav.blog', posts_path, controller: 'front/posts') %>
          <%= nav_entry('front.nav.about', about_page_path, controller: 'front/static', action: 'about') %>
          <%= nav_entry('front.nav.contact', contact_page_path,   controller: 'front/static', action: 'contact') %>
        </ul>
      </nav>
    </div>
  </div>

  <% if content_for?(:site_header) %>
    <div id="page-title" class="row">
      <div class="nine columns text-center">
        <%= yield(:site_header) %>
      </div>
    </div>
  <% end %>
</header>

<%= yield %>

<footer>
  <div class="row">
    <div class="twelve columns">
      <ul class="footer-nav">
        <%= nav_entry('front.nav.blog', posts_path, controller: 'front/posts') %>
        <%= nav_entry('front.nav.about', about_page_path, controller: 'front/static', action: 'about') %>
        <%= nav_entry('front.nav.contact', contact_page_path,   controller: 'front/static', action: 'contact') %>
      </ul>

      <ul class="footer-social">
        <% %w(facebook youtube instagram twitter google_plus rss).each do |social_type|
          caption("social.#{social_type}.url") do |social_url| %>
            <li><a href="<%= social_url %>"><i class="fa fa-<%= social_type.dasherize %>"></i></a></li>
          <% end end %>
      </ul>

      <ul class="copyright">
        <li>Copyright &copy; 2018 <%= caption('site.author') %></li>
        <li>Design by <a href="http://www.styleshout.com/">Styleshout</a></li>
      </ul>
    </div>

    <div id="go-top">
      <a title="<%= t('front.nav.back_to_top') %>" href="#"><%= t('front.nav.back_to_top') %></a>
    </div>
  </div>
</footer>

</body>
</html>